### ISSUE TITLE
Can't have same video on same page

### ISSUE THREAD

**Issue by p-m-p** [SproutVideo/sproutvideo-player-api#4]
Hi, we're having issues using the player with two (or more) instances of the same video on the same page. Essentially the player is identified by the video id and when a second is added to the page messages are sent to the latter and the former no longer receives any events.

**Comment by podman** [comment]
This is not a bug but likely an issue with your implementation. Please contact our support team at support@sproutvideo.com for help. We don't use Github Issues for general technical support. Thanks!

**Comment by p-m-p** [comment]
I'm afraid it's definitely a shortcoming of the player code which stores each registered player in `SV.players` object using the video/playlist id. Hence if you put two of the same video or playlist in a single document the last player created receives all messages for that id.

I've had to patch this locally where we keep the players in an array and check the message source against the players iframe.

**Comment by podman** [comment]
Let's take this conversation off GitHub. Please email us at support@sproutvideo.com and we'll help you with your implementation.
